// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import GrainController from "./grain_controller"
application.register("grain", GrainController)

import HeroController from "./hero_controller"
application.register("hero", HeroController)

import HoverViewController from "./hover_view_controller"
application.register("hover-view", HoverViewController)

import ImageSpinnerController from "./image_spinner_controller"
application.register("image-spinner", ImageSpinnerController)

import MarkdownController from "./markdown_controller"
application.register("markdown", MarkdownController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import WorkfilterController from "./workfilter_controller"
application.register("workfilter", WorkfilterController)
